INSERT INTO categories (name_en, name_ro, name_ru, slug_en, slug_ro, slug_ru)
VALUES
('All events', 'Toate evenimente', 'Все события', 'all-events', 'toate-evenimente', 'все-события'),
('Concerts', 'Concerte', 'Концерты', 'concerts', 'concerte', 'концерты'),
('Theatre', 'Teatru', 'Театр', 'theatre', 'teatru', 'театр'),
('Movies', 'Filme', 'Фильмы', 'movies', 'filme', 'фильмы'),
('Shows', 'Spectacole', 'Шоу', 'shows', 'spectacole', 'шоу'),
('Arena Chisinau', 'Arena Chisinau', 'Арена Кишинэу', 'arena-chisinau', 'arena-chisinau', 'арена-кишинэу'),
('Cultural voucher', 'Voucer Cultural', 'Культурный ваучер', 'cultural-voucher', 'voucer-cultural', 'культурный-ваучер'),
('For kids', 'Pentru copii', 'Для детей', 'for-kids', 'pentru-copii', 'для-детей'),
('Trainings', 'Treininguri', 'Тренинги', 'trainings', 'treininguri', 'тренинги'),
('Sport', 'Sport', 'Спорт', 'sport', 'sport', 'спорт'),
('Afisha recommends', 'Afisha Recomanda', 'Афиша рекомендует', 'afisha-recommends', 'afisha-recomanda', 'афиша-рекомендует'),
('Various', 'Diverse', 'Разное', 'various', 'diverse', 'разное'),
('Parties', 'Petreceri', 'Вечеринки', 'parties', 'petreceri', 'вечеринки'),
('News', 'Noutati', 'Новости', 'news', 'noutati', 'новости'),
('Places', 'Locuri', 'Места', 'places', 'locuri', 'места'),
('About project', 'Despre proiect', 'О проекте', 'about-project', 'despre-proiect', 'о-проекте');


INSERT INTO events (
    title_en, title_ro, title_ru,
    category_id, slug_en, slug_ro, slug_ru,
    date_event, time_event,
    location_en, location_ro, location_ru,
    image, price, created_at, updated_at
)
VALUES
(
    'Rock Concert by The Rockers',
    'Concert Rock de The Rockers',
    'Рок-концерт группы The Rockers',
    2,
    'rock-concert-by-the-rockers',
    'concert-rock-de-the-rockers',
    'rok-koncert-gruppy-the-rockers',
    '2025-09-15',
    '19:00:00',
    'Chisinau Arena',
    'Arena Chisinau',
    'Арена Кишинэу',
    'rock.jpg',
    750.00,
    NOW(),
    NOW()
),
(
    'Shakespeare Play',
    'Piesa Shakespeare',
    'Пьеса Шекспира',
    3,
    'shakespeare-play',
    'piesa-shakespeare',
    'piesa-shekspira',
    '2025-11-20',
    '18:00:00',
    'National Theatre',
    'Teatrul Național',
    'Национальный театр',
    'theatre.jpg',
    500.00,
    NOW(),
    NOW()
),
(
    'Movie Premiere',
    'Premiera Filmului',
    'Премьера фильма',
    4,
    'movie-premiere',
    'premiera-filmului',
    'premiera-filma',
    '2025-12-05',
    '20:00:00',
    'Cinema City',
    'Cinema City',
    'Кинотеатр Сити',
    'movie.jpg',
    600.00,
    NOW(),
    NOW()
),
(
    'Kids Festival',
    'Festival Pentru Copii',
    'Детский фестиваль',
    8,
    'kids-festival',
    'festival-pentru-copii',
    'detskiy-festival',
    '2025-10-10',
    '10:00:00',
    'City Park',
    'Parcul Orașului',
    'Городской парк',
    'images/events/kids.jpg',
    250.00,
    NOW(),
    NOW()
),
(
    'Sports Tournament',
    'Turneu Sportiv',
    'Спортивный турнир',
    10,
    'sports-tournament',
    'turneu-sportiv',
    'sportivnyy-turnir',
    '2025-09-25',
    '14:00:00',
    'Sports Arena',
    'Arena Sportivă',
    'Спортивная арена',
    'sport.jpg',
    420.00,
    NOW(),
    NOW()
);


INSERT INTO events (category_id, title_en, title_ro, title_ru, slug_en, slug_ro, slug_ru, date, description_en, description_ro, description_ru, image)
VALUES
(1, 'All Events Example', 'Exemplu Toate Evenimente', 'Пример Все события', 'all-events-example', 'exemplu-toate-evenimente', 'пример-все-события', '2025-11-15', 'Description EN', 'Descriere RO', 'Описание RU', 'all-events.jpg'),
(2, 'Concert Rock', 'Concert Rock', 'Рок Концерт', 'concert-rock', 'concert-rock', 'рок-концерт', '2025-11-16', 'Description EN', 'Descriere RO', 'Описание RU', 'concert.jpg'),
(3, 'Theatre Play', 'Piesa de teatru', 'Театральная пьеса', 'theatre-play', 'piesa-teatru', 'театральная-пьеса', '2025-11-17', 'Description EN', 'Descriere RO', 'Описание RU', 'theatre.jpg'),
(4, 'Movie Premiere', 'Premiera Film', 'Премьера фильма', 'movie-premiere', 'premiera-film', 'премьера-фильма', '2025-11-18', 'Description EN', 'Descriere RO', 'Описание RU', 'movie.jpg'),
(5, 'Magic Show', 'Spectacol Magic', 'Магическое шоу', 'magic-show', 'spectacol-magic', 'магическое-шоу', '2025-11-19', 'Description EN', 'Descriere RO', 'Описание RU', 'show.jpg'),
(6, 'Arena Concert', 'Concert Arena', 'Концерт Арена', 'arena-concert', 'concert-arena', 'концерт-арена', '2025-11-20', 'Description EN', 'Descriere RO', 'Описание RU', 'arena.jpg'),
(7, 'Cultural Voucher Event', 'Eveniment Voucer Cultural', 'Событие Культурный Ваучер', 'cultural-voucher-event', 'eveniment-voucer-cultural', 'событие-культурный-ваучер', '2025-11-21', 'Description EN', 'Descriere RO', 'Описание RU', 'voucher.jpg'),
(8, 'Kids Workshop', 'Atelier Pentru Copii', 'Мастер-класс Для Детей', 'kids-workshop', 'atelier-pentru-copii', 'мастер-класс-для-детей', '2025-11-22', 'Description EN', 'Descriere RO', 'Описание RU', 'kids.jpg'),
(9, 'Training Session', 'Sesiune de Training', 'Тренинг', 'training-session', 'sesiune-training', 'тренинг', '2025-11-23', 'Description EN', 'Descriere RO', 'Описание RU', 'training.jpg'),
(10, 'Sport Event', 'Eveniment Sportiv', 'Спортивное событие', 'sport-event', 'eveniment-sportiv', 'спортивное-событие', '2025-11-24', 'Description EN', 'Descriere RO', 'Описание RU', 'sport.jpg'),
(11, 'Afisha Recommends', 'Afisha Recomanda', 'Афиша рекомендует', 'afisha-recommends', 'afisha-recomanda', 'афиша-рекомендует', '2025-11-25', 'Description EN', 'Descriere RO', 'Описание RU', 'afisha.jpg'),
(12, 'Various Event', 'Eveniment Divers', 'Разное событие', 'various-event', 'eveniment-divers', 'разное-событие', '2025-11-26', 'Description EN', 'Descriere RO', 'Описание RU', 'various.jpg'),
(13, 'Party Night', 'Noapte de Petrecere', 'Вечеринка', 'party-night', 'noapte-petrecere', 'вечеринка', '2025-11-27', 'Description EN', 'Descriere RO', 'Описание RU', 'party.jpg'),
(14, 'News Event', 'Eveniment Noutati', 'Новостное событие', 'news-event', 'eveniment-noutati', 'новостное-событие', '2025-11-28', 'Description EN', 'Descriere RO', 'Описание RU', 'news.jpg'),
(15, 'Places Visit', 'Vizita Locuri', 'Посещение мест', 'places-visit', 'vizita-locuri', 'посещение-мест', '2025-11-29', 'Description EN', 'Descriere RO', 'Описание RU', 'places.jpg'),
(16, 'About Project Event', 'Eveniment Despre Proiect', 'Событие О Проекте', 'about-project-event', 'eveniment-despre-proiect', 'событие-о-проекте', '2025-11-30', 'Description EN', 'Descriere RO', 'Описание RU', 'about.jpg');
